[project]
name = "browser-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "google-genai>=1.35.0",
    "mcp-agent>=0.0.14",
    "openai>=1.0.0",
    "streamlit>=1.28.0",
]
